### ISSUE TITLE
Begin Encounter doesn't take into account with Eidolons

### ISSUE THREAD

**Issue by Ruidolph** [Eligarf/avoid-notice#12]
So I have Pf2e Perception as well as Pf2e Avoid Notice. Because Eidolons are excluded from initiative when combat begins and the tokens are revealed, the eidolon can still see everything. Is there any way to implement that or a workaround?

**Comment by Eligarf** [comment]
I'll have a look at it - I was able to get familiars to behave properly, so in theory I should be able to make these work as well...
