### ISSUE TITLE
Feature request/Bug - Hazards should be excluded from the process

### ISSUE THREAD

**Issue by roi007leaf** [Eligarf/avoid-notice#15]
Love the module!
Can you please exclude hazards from the visibility calculation? pf2e perception doesnt support it for hazards

**Comment by Ruidolph** [comment]
I'm also having this issue.

**Comment by Eligarf** [comment]
Could either of you give me an export of a hazard you are having difficulty with? This is the first I've heard of hazard tokens

**Comment by Ruidolph** [comment]
Hazards are often placed on the map in Adventure Path's and you have to add them to combat and roll for their initiative using stealth. Here's an example of one from Abomination Vaults.
[fvtt-Actor-blood-of-belcorra-XLTPZ592Z9MXXBlA.json](https://github.com/user-attachments/files/17007705/fvtt-Actor-blood-of-belcorra-XLTPZ592Z9MXXBlA.json)

**Comment by Eligarf** [comment]
I derped - I have another module for 5e/pf1 that I thought this bug was for. Thanks, I'll look into the issue
