### ISSUE TITLE
Module Literally does Nothing

### ISSUE THREAD

**Issue by Agnestorm** [Eligarf/avoid-notice#17]
On latest version of v12, fresh PF2e world with this module only installed and even when I click begin encounter, absolutely nothing happens to the stealth initiative chat roll.

**Comment by Eligarf** [comment]
PC's have to have the Avoid Notice exploration activity set as active (also means they have to be in the 'party' group in the actor sidebar)

**Comment by Eligarf** [comment]
1.6.0 will have a setting allowing you to choose whether or not you want the exploration activity as a requirement, and will put a note on PCs that roll stealth without using Avoid Notice that they won't automatically hide at combat start.

**Comment by Agnestorm** [comment]
Got it, thank you for the explanation.
