### ISSUE TITLE
can't disable 'required avoid notice'

### ISSUE THREAD

**Issue by KaZlos** [Eligarf/avoid-notice#19]
the option to require avoid notice is disabled yet the module still returns the "you need to use avoid notice..." in chat
only modules used are on screenshot (the same issue seems to happen with all other modules and pf2e perception too)

![image](https://github.com/user-attachments/assets/6b45731b-4e26-40ac-99a2-4ec748555e4a)

**Comment by KaZlos** [comment]
same thing if the require option is checked

**Comment by Eligarf** [comment]
Fixed the hideous typo that caused this in 1.7.0
