### ISSUE TITLE
Version Tagging Incorrect on FVTT

### ISSUE THREAD

**Issue by ChasarooniZ** [Eligarf/avoid-notice#26]
![image](https://github.com/user-attachments/assets/843b52f9-3397-4740-b46a-ca8b95941920)
Should be `1.11.0` etc.., but it messes up what shows as latest version

Also your manifest URLs all point to the most recent version and not the version they're attached to making them not useful as a way to grab older versions

*helpful module btw appreciate it 😄*

**Comment by Eligarf** [comment]
Those accidental version prefixes are the only thing I can't edit in the foundry package manager. I've tried to fix them, but it seems I'm stuck with them. It makes no sense to me why they sort to the top - if anything they should sort to the bottom, but no. They mock me every time I publish a new version.

**Comment by ChasarooniZ** [comment]
Hahahahaha, that made me laugh out loud. That sounds really annoying, and when you say it they really should be on the bottom. You might have some luck actually if you reach out to the foundry modules team and they may be able to edit it on the back end for you
