### ISSUE TITLE
Wrong condition

### ISSUE THREAD

**Issue by Mamutito** [Eligarf/avoid-notice#8]
Hi Eligarf, amazing module, i want point out that, when you failed your stealth check you are not observed, you are hidden, only when critical failure happen you are observed.

So vs Perception DC:

Unnoticed if u beat init and perception DC as you said in the options.
Success: You are Undetected.
Failure: You are Hidden.
Critical Failure: You are Observed.

I'm using pf2e perception too.

Thanks!.

**Comment by Eligarf** [comment]
Thanks for reporting it, I missed the subtle use of Sneak vs Hide in the initiative rule for failure cases; I guess our group was playing this wrong!

Fixed in 1.2.3
